// Generated by ts-to-zod
import { z } from 'zod';

const ruleSchema = z
  .object({
    releaseByPercentage: z.number().gte(0).lte(100).optional(),
    individualTargets: z.record(z.boolean()).optional(),
  })
  .strict();

const namespacedRuleSchema = z.record(ruleSchema);

export const featureReleaseConfigSchema = z.record(
  z.union([ruleSchema, namespacedRuleSchema])
);
